name: Test

on:
  push:
    branches:
      - homework_vectors
  pull_request:
    branches:
      - homework_vectors

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download JSON vectors
        run: |
          curl -L https://drive.google.com/uc?export=download&id=13hA0TAJ9qy51Dopdvhtvd8u7IrayvPZM -o homework_vectors/word_embeddings.json
      - name: Run tests
        run: |
          python -m pytest -vv